### ISSUE TITLE
CDN

### ISSUE THREAD

**Issue by trishankatdatadog** [secure-systems-lab/peps#12]
Can we use relative filenames for packages, or do we need to point to absolute locations?

**Comment by mnm678** [comment]
I believe this was addressed here: https://github.com/secure-systems-lab/peps/pull/3/files. Is there anywhere else that I should clarify this?

**Comment by trishankatdatadog** [comment]
@lukpueh is working on this

**Comment by trishankatdatadog** [comment]
Closed by #18
