### ISSUE TITLE
Disambiguate bin-n metadata even more

### ISSUE THREAD

**Issue by trishankatdatadog** [secure-systems-lab/peps#15]
- [x] Why doesn't targets delegate directly to bin-n roles? What is the benefit of having an intermediate bins role? The only purpose I can see is semantic. Delegating from targets directly to bin-n would reduce complexity of this pep.

- [x] What is the difference between revoking trust in projects and revoking it in versions? If I understand correctly in both cases, the target files corresponding to that project or version need to be removed from the bin-n metadata they are listed in, which need to be re-signed with the online key. If that's accurate, why differentiate?

- [x] Also, is there a case where the bins role (offline key) needs to be resigned?

- [x] Disambiguate bins and bin-n in table.

- [x] Clarify what "projects targets metadata" is (paragraph under the table).

- [x] Maybe re-think the table. There are multiple instances that describe how,
snapshot, timestamp and/or bin-n roles need to cooperate for an attacker to be successful, which seems less meaningful when these roles share the same online key, which is recommend in this pep.

**Comment by lukpueh** [comment]
Transferring https://github.com/secure-systems-lab/peps/pull/8#issuecomment-540644059 by @JustinCappos:

> Why doesn't targets delegate directly to bin-n roles? What is the benefit of having an intermediate bins role? The only purpose I can see is semantic. Delegating from targets directly to bin-n would reduce complexity of this pep.

It also makes it easier to revoke a single key or change the top level targets (to transition to PEP 480).  You don't need to re-download the bins -> bin-n mapping in this case, which is fairly large.

> What is the difference between revoking trust in projects and revoking it in versions? If I understand correctly in both cases, the target files corresponding to that project or version need to be removed from the bin-n metadata they are listed in, which need to be re-signed with the online key. If that's accurate, why differentiate?

It's the same in PEP 458.  They are different in PEP 480, which was what I was thinking of with my original PR, so this should be fixed.

> Also, is there a case where the bins role (offline key) needs to be resigned?

Not unless there was a weakness in how the keys were generated.

**Comment by lukpueh** [comment]
> It also makes it easier to revoke a single key or change the top level targets (to transition to PEP 480). You don't need to re-download the bins -> bin-n mapping in this case, which is fairly large.

Okay, in the face of PEP 480, where top-level *targets* delegates to more than one roles, this makes sense.  Is it worth mentioning this in PEP 458?

Also, just to make sure that we are on the same page, in PEP 458, it does not make it easier to revoke a single key, right? 

Speaking of PEP 480, the diagram in PEP 458's "Maximum Security Model" section shows the *unclaimed* role (i.e. *bins*) as being signed by an online key. Should we change this? Or should we just remove the section, given that the subsequent section, i.e. "End-to-End Signing", points to PEP 480 anyway?

**Comment by joshuagl** [comment]
> Speaking of PEP 480, the diagram in PEP 458's "Maximum Security Model" section shows the _unclaimed_ role (i.e. _bins_) as being signed by an online key. Should we change this? Or should we just remove the section, given that the subsequent section, i.e. "End-to-End Signing", points to PEP 480 anyway?

FWIW I think this section should be removed, the maximum security model is mentioned in the end-to-end signing section and PEP 480 is the best location for details of that model.

**Comment by JustinCappos** [comment]
Agreed, let's remove it.

**Comment by trishankatdatadog** [comment]
Closing because breaking into separate issues
