### ISSUE TITLE
Metadata scalability: more detail on hashed bins

### ISSUE THREAD

**Issue by joshuagl** [secure-systems-lab/peps#19]
Caveat: I'm reviewing the PEP as a non-expert in attempt to help improve clarity, I hope these comments are useful.

Having read the ["Metadata Scalability"](https://github.com/secure-systems-lab/peps/blob/0c20efe96098be0d4eaeb56a58007e020fa4e71b/pep-0458.txt#L433) section of the PEP and the ["Delegate to Hashed Bins"](https://github.com/theupdateframework/tuf/blob/v0.11.1/docs/TUTORIAL.md#delegate-to-hashed-bins) section of the TUF tutorial, I can help but feel there's some detail missing on the hashed bins proposal.

As a reader looking to implement the PEP I'd like to better understand:
- when should the number of bins increase?
- are changes to the number of bins transparent to the client? i.e. does changing the number of bins require some kind of synchronisation between PyPI and its clients?

**Comment by joshuagl** [comment]
The first question is at least partially answered by @trishankatdatadog in #29, the number of bins should increase when the number of targets increases to 4X the current number.

I think the second question is also answered indirectly - the changes to the number of bins is transparent, the client will be required to download a fresh set of metadata (as though it were a new user) but wouldn't require any explicit code logic or user interaction to do so.

Is my inference correct?

**Comment by trishankatdatadog** [comment]
@joshuagl yes 💯

**Comment by lukpueh** [comment]
Fixed with #37
