### ISSUE TITLE
Metadata scalability: compression

### ISSUE THREAD

**Issue by joshuagl** [secure-systems-lab/peps#20]
Caveat: I'm reviewing the PEP as a non-expert in attempt to help improve clarity, I hope these comments are useful.

The PEP suggests that PyPI SHOULD provide a compressed version of _snapshot_ metadata, it would be valuable to include some more specific recommendations and guidance on how to go about doing so. Particularly with regards to the grave warnings around the perils of compression in [TAP 10](https://github.com/theupdateframework/taps/blob/master/tap10.md).

**Comment by joshuagl** [comment]
Having read the discussions [leading up to](https://groups.google.com/forum/#!msg/theupdateframework/I7kI6Wp1A7k/94Ggjr4YAgAJ) and [around](https://github.com/theupdateframework/taps/issues/52) TAP10 it appears the recommendation from TUF is to handle compression of metadata files at a separate layer, i.e. HTTP transport.

PyPI/Warehouse already supports compression of HTTP responses ([enabled here](https://github.com/pypa/warehouse/blob/5c2a00bd6f0d6077e1de1cdb3d763c4fa36949cb/warehouse/config.py#L412) and [implemented here](https://github.com/pypa/warehouse/blob/5c2a00bd6f0d6077e1de1cdb3d763c4fa36949cb/warehouse/utils/compression.py#L23)) and I infer from my research that this should be enough for the snapshot metadata? 

In which case the action for this issue would be to clarify this item in the PEP:
> Due to the large number of delegated metadata, compressed versions of *snapshot* metadata SHOULD also be made available to clients.

Perhaps with a simple change like:
> Due to the large number of delegated metadata, compressed versions of *snapshot* metadata SHOULD also be made available to clients via the existing Warehouse mechanisms for HTTP compression.

?

**Comment by lukpueh** [comment]
To me that sounds good. TAP 10 does recommend to move down to the presentation layer, which IIUC is where http compression is located at. 

I wonder if it's worth mentioning that TUF itself does not provide compression, due to the reasons listed in TAP 10. But probably it just adds noise.

I suggest you PR what you have. 

Also, thanks for linking to the relevant discussions, that's very helpful!

**Comment by lukpueh** [comment]
Fixed with #30
