### ISSUE TITLE
Managing Keys: demystify the offline ceremony

### ISSUE THREAD

**Issue by joshuagl** [secure-systems-lab/peps#22]
Note: I'm reviewing the PEP as a non-expert in attempt to help improve clarity, I hope these comments are useful.

Between the term "ceremony" and the lack of reasoning for some of the steps the management of offline keys as described feels mysterious.

For example, why should we "Print and save cryptographic hashes of new TUF metadata"? Under what circumstances will those printouts be used?

**Comment by trishankatdatadog** [comment]
@joshuagl Can you help fix this please? We can walk you through our reasons.

Let's make a shared channel on Slack somewhere for this?

**Comment by joshuagl** [comment]
@trishankatdatadog I can absolutely help fix this. I'm on CNCF Slack if that helps? If you have another Slack server you'd prefer to use I'd be open to discussing elsewhere.

**Comment by lukpueh** [comment]
Just read through the ceremony section again and I think it is already pretty solid. Not sure if this is what @joshuagl had in mind but here are a few comments/questions regarding [L630-L640](https://github.com/secure-systems-lab/peps/blob/91a35fa100bfa3dbbc5975fd9565e936239c4e81/pep-0458.txt#L630-L640). 

@trishankatdatadog, let me know what you had in mind when writing those lines. I can try updating the text then. 


> In order to minimize OPSEC__ errors during the ceremony, scripts SHOULD be
written to automate tedious parts, such as:

Are these all scripts that should run on the key generation computer?

>  - Exporting to sneakernet__ all code and data (e.g., previous TUF metadata, 
   targets, and *root* keys) required to generate new keys and replace old ones 

Does exporting code mean that you write code on that computer? Shouldn't the scripts mentioned above rather be (or import) the code used to generate keys etc.?


> - Printing and saving cryptographic hashes of new TUF metadata  

... as additional paper backup, e.g. to compare in the case of a compromise? (Maybe we can put this at the end of the list, after "export ... to backup media"?)

> - Exporting *all* new TUF metadata, targets, and keys to encrypted backup media 
> - Exporting *only* new TUF metadata, targets, and online keys to encrypted backup 
   media 

Why do you differ between "*all* new" and "*only* new"? Also, do you really have actual target files on the key generation computer?

**Comment by trishankatdatadog** [comment]
> Are these all scripts that should run on the key generation computer?

Yes

> Does exporting code mean that you write code on that computer? Shouldn't the scripts mentioned above rather be (or import) the code used to generate keys etc.?

You write the code on online computer, then export it unto, say, USB, to be imported into offline computer. Makes sense?

> ... as additional paper backup, e.g. to compare in the case of a compromise? (Maybe we can put this at the end of the list, after "export ... to backup media"?)

Ok

> Why do you differ between "all new" and "only new"? Also, do you really have actual target files on the key generation computer?

On some backup media, you want ALL keys. On some backup media, you want only the online keys to be imported into the Python infrastructure.

Also, yes, you want actual target files on the key generation computer if you want to populate all the bin-n roles with hashes.

**Comment by lukpueh** [comment]
> Also, yes, you want actual target files on the key generation computer if you want to populate all the bin-n roles with hashes.

But why populate bin-n metadata during key ceremony? Aren't target files signed for by bin-n roles with online keys as they are uploaded? Don't you only sign *bins* and *targets*?

**Comment by trishankatdatadog** [comment]
Yeah, probably operationally simplest. At some point, though, PyPI does have to add and sign all the bin-n metadata, and you're right that a one-time online initialization is the simplest. Please feel free to add a sentence or two to clarify this, if you like. Thanks!

**Comment by joshuagl** [comment]
> Yeah, probably operationally simplest. At some point, though, PyPI does have to add and sign all the bin-n metadata, and you're right that a one-time online initialization is the simplest. Please feel free to add a sentence or two to clarify this, if you like. Thanks!

In which case, we should:
- remove references to targets being required on the air gapped key-signing machine
  - clarify what data are required on the air gapped key-signing machine - root keys (to do the signing), metadata to sign with the newly generated keys, ???
- discuss a one-time online initialisation mechanism for signing target files (when TUF is first enabled?)

**Comment by joshuagl** [comment]
joshuagl/peps@3de83ee includes some preliminary work to clarify this section

**Comment by trishankatdatadog** [comment]
closed with #52
