### ISSUE TITLE
Why doesn't targets delegate directly to bin-n roles?

### ISSUE THREAD

**Issue by trishankatdatadog** [secure-systems-lab/peps#23]
Why doesn't targets delegate directly to bin-n roles? What is the benefit of having an intermediate bins role? The only purpose I can see is semantic. Delegating from targets directly to bin-n would reduce complexity of this pep.

**Comment by lukpueh** [comment]
@JustinCappos  wrote https://github.com/secure-systems-lab/peps/pull/8#issuecomment-540644059: 
It also makes it easier to revoke a single key or change the top level targets (to transition to PEP 480). You don't need to re-download the bins -> bin-n mapping in this case, which is fairly large.

**Comment by lukpueh** [comment]
@lukpueh replied https://github.com/secure-systems-lab/peps/issues/15#issuecomment-541070822:
Okay, in the face of PEP 480, where top-level targets delegates to more than one roles, this makes sense. Is it worth mentioning this in PEP 458?

Also, just to make sure that we are on the same page, in PEP 458, it does not make it easier to revoke a single key, right?

**Comment by lukpueh** [comment]
#40 is my stab at this.
