### ISSUE TITLE
What is the difference between revoking trust in projects and revoking it in versions?

### ISSUE THREAD

**Issue by trishankatdatadog** [secure-systems-lab/peps#24]
What is the difference between revoking trust in projects and revoking it in versions? If I understand correctly in both cases, the target files corresponding to that project or version need to be removed from the bin-n metadata they are listed in, which need to be re-signed with the online key. If that's accurate, why differentiate?

**Comment by JustinCappos** [comment]
I'd appreciate a review on this commit.  Any takers?

**Comment by lukpueh** [comment]
Just commented on fbc326b.

**Comment by trishankatdatadog** [comment]
Guys, sorry, I'm confused.

1. Why not review a PR instead of a commit to a branch?
2. Why are we merging 2nd-draft PRs / commits to the 1st-draft branch / PR which has not yet been fully reviewed upstream?

**Comment by JustinCappos** [comment]
> Guys, sorry, I'm confused.
> 
> 1. Why not review a PR instead of a commit to a branch?
> 2. Why are we merging 2nd-draft PRs / commits to the 1st-draft branch / PR which has not yet been fully reviewed upstream?

Likely because I screwed up.  I have three urgent things that are competing for time here and wasn't paying enough attention to the workflow.  What's the best way to get us back to a normal workflow given where we are at?

**Comment by trishankatdatadog** [comment]
Understood, Justin. Let's just continue to merge to the `1st-draft` branch.

**Comment by trishankatdatadog** [comment]
Please close this if you think it's been fixed, thanks

**Comment by lukpueh** [comment]
> 2. Why are we merging 2nd-draft PRs / commits to the 1st-draft branch / PR which has not yet been fully reviewed upstream?

@trishankatdatadog, I changed the target of Justin's PR #31 from `master` to `1st-draft`. I thought that's what you suggested on slack earlier this week. Sorry if I misunderstood.

**Comment by joshuagl** [comment]
> > 1. Why are we merging 2nd-draft PRs / commits to the 1st-draft branch / PR which has not yet been fully reviewed upstream?
> 
> @trishankatdatadog, I changed the target of Justin's PR #31 from `master` to `1st-draft`. I thought that's what you suggested on slack earlier this week. Sorry if I misunderstood.

That was my interpretation of the request too. All of my PRs are using the `1st-draft` branch as a base...

**Comment by trishankatdatadog** [comment]
No problem, guys. I should have made this clearer.
