### ISSUE TITLE
Clarify what "projects targets metadata"

### ISSUE THREAD

**Issue by trishankatdatadog** [secure-systems-lab/peps#27]
Clarify what "projects targets metadata" is (paragraph under the table).

**Comment by lukpueh** [comment]
https://github.com/secure-systems-lab/peps/blob/24dea57d9766b303e5a102cff5456c5d7ffc9687/pep-0458.txt#L874-L875

https://github.com/secure-systems-lab/peps/blob/24dea57d9766b303e5a102cff5456c5d7ffc9687/pep-0458.txt#L884

Is "project" in above snippets an interference from PEP 480? To me it sounds like one of the bottom-level targets roles (Requests, Numpy, Django, etc.) delegated to by *claimed* and *recently-claimed*.

Here in PEP 458 we don't have *project* roles, we only have anonymous *bin-n* roles.

**Comment by trishankatdatadog** [comment]
@lukpueh yes, looks like a premature reference to PEP 480, let's nuke them from orbit, to be sure

**Comment by lukpueh** [comment]
@mnm is fixing this in #43. Thanks!

**Comment by JustinCappos** [comment]
Closed by #43
