### ISSUE TITLE
Rethink the security analysis table

### ISSUE THREAD

**Issue by trishankatdatadog** [secure-systems-lab/peps#28]
Maybe re-think the table. There are multiple instances that describe how,
snapshot, timestamp and/or bin-n roles need to cooperate for an attacker to be successful, which seems less meaningful when these roles share the same online key, which is recommend in this pep.

**Comment by JustinCappos** [comment]
Chatted with @mnm678 about this and #26 .  She'll make a new table that is more accurate in conveying that to ease operational burden some keys may be shared (so will be compromised together).  She will collapse the table and move the current one to PEP 480.

**Comment by JustinCappos** [comment]
Closed by #43
