### ISSUE TITLE
Appendix C appears to be unreferenced

### ISSUE THREAD

**Issue by joshuagl** [secure-systems-lab/peps#36]
Is "Appendix C: PEP 470 and Projects Hosted Externally" still useful? It doesn't appear to be referenced anywhere in the body of PEP 458.

If not I'll open a PR, or update #35, to remove it.

**Comment by trishankatdatadog** [comment]
Let's replace that entire text to note that:

1. By default, new versions of pip going forward SHOULD NOT support installing packages from PyPI w/o TUF.
2. Those who absolutely need to use TUF on repos other than PyPI SHOULD consult [TAP 4](https://github.com/theupdateframework/taps/blob/master/tap4.md).

Thanks!

**Comment by trishankatdatadog** [comment]
closed by #42
