### ISSUE TITLE
Criteria for cost for new users

### ISSUE THREAD

**Issue by trishankatdatadog** [secure-systems-lab/peps#45]
[@ewdurbin](https://github.com/python/peps/pull/1203#discussion_r336227672): 'What is the criteria that we would use to determine that the cost for new users is "too much"? Is it the initial download size of the metadata?'

**Comment by joshuagl** [comment]
Looks like this was addressed in #50. Let's close this issue.

**Comment by trishankatdatadog** [comment]
closed with #50
