### ISSUE TITLE
Add a transition plan

### ISSUE THREAD

**Issue by trishankatdatadog** [secure-systems-lab/peps#47]
Might be wise to discuss a transition plan to slowly but surely migrate pip users to PEP 458 instead of turning it on full-blast all at once. This plan should also discuss how users can temporarily disable using PEP 458 in case of unforeseen issues (such as fixing a bug that requires downloading and installing an update of pip in the first place).

**Comment by trishankatdatadog** [comment]
There needs to be a way for users to share pertinent information when Things Go Wrong™️.

Error messages for users also need to be friendly and readable.

**Comment by brainwane** [comment]
@JustinCappos I think this (and #56) deserve discussion in [the Discourse thread](https://discuss.python.org/t/pep-458-secure-pypi-downloads-with-package-signing/2648/) for potential incorporation into the PEP -- could I ask you to suggest it there?

**Comment by JustinCappos** [comment]
Do you just want me to ask someone from our group to add such text or were
you looking for more of a draft?

**Comment by brainwane** [comment]
Good point. @mnm678 ^ could you please summarize/share this/#56 in the Discourse thread to open the transition plan up for discussion there?

**Comment by brainwane** [comment]
Marina [did this](https://discuss.python.org/t/pep-458-secure-pypi-downloads-with-package-signing/2648/58); thanks!

**Comment by mnm678** [comment]
Closing based on conversation on [Discourse](https://discuss.python.org/t/pep-458-secure-pypi-downloads-with-package-signing/2648/57) as out of scope for this PEP.
