### ISSUE TITLE
Use consistent terminology

### ISSUE THREAD

**Issue by trishankatdatadog** [secure-systems-lab/peps#57]
- [ ] "Distribution" instead of "package"

**Comment by joshuagl** [comment]
PyPI is the Python Package Index and pip is a tool for installing packages. Is distribution the correct term? Is a distribution is the package + metadata? Or should we opt to consistently use package?

**Comment by lukpueh** [comment]
From PEP 458's glossary:
> * Distributions: Distributions are the packaged files that are used to publish and distribute a release [17]_.

(the reference points to the withdrawn [PEP 426](https://www.python.org/dev/peps/pep-0426/))

Should we ask the Python folks what to best use?

At any rate, we should address [Dustin's comment](https://github.com/python/peps/pull/1203#discussion_r340884004) about clarifying that "target files" (tuf speak) are "release files or artifacts" (python speak).

**Comment by trishankatdatadog** [comment]
@lukpueh Yes, could you ask @di?

**Comment by di** [comment]
The glossary at https://packaging.python.org/glossary/ might be helpful. I think the best terminology to use here would be "distribution files".
