### ISSUE TITLE
Clarify what "multiple target files" mean

### ISSUE THREAD

**Issue by trishankatdatadog** [secure-systems-lab/peps#60]
@di [said](https://github.com/python/peps/pull/1203#discussion_r340885361): `If I understand correctly, this means that the size of PyPI's "on disk" size for target files must grow 3x: once for the existing files (to maintain backwards compatibility), once for the SHA2-256 hash and once for the SHA2-512 hash. Correct? If so I think this should probably be noted in the "What Additional Repository Files are Required on PyPI?" section above.`

I think it makes sense to also address in the same PR something else @di [said](https://github.com/python/peps/pull/1203#discussion_r340884004): `I think "target file" could stand to be defined here. We usually refer to these as "release files" or "artifacts" when working on PyPI/pip, so drawing the parallel here would be helpful.`

**Comment by lukpueh** [comment]
Let's add "target files" to the Definitions section. And let's do it in a separate PR or together with #57.
