### ISSUE TITLE
Replace "--no-pep-458" with something stronger

### ISSUE THREAD

**Issue by trishankatdatadog** [secure-systems-lab/peps#61]
@di [said](https://github.com/python/peps/pull/1203#discussion_r340868848): `I think that the example we give here has a high likelihood of becoming the actual flag that pip implements. The current example (--no-pep-458) is obscure enough that a user could be convinced to use it without realizing the effect it has. I think we should use an example flag that is more clear about the outcome, such as --unsafely-disable-package-verification, or something similar.`

**Comment by joshuagl** [comment]
Why are we recommending the option be undocumented? I think it should be documented, so that we can make clear the implications of using it.

**Comment by trishankatdatadog** [comment]
Not undocumented, but clearer / better name

**Comment by joshuagl** [comment]
What do you think of `--disable-integrity-verification`, `--disable-verification` or `--disable-tamper-resistance`?

**Comment by trishankatdatadog** [comment]
closed with #62
