### ISSUE TITLE
Hash algorithm transition plan

### ISSUE THREAD

**Issue by mnm678** [secure-systems-lab/peps#68]
[dstufft](https://github.com/python/peps/pull/1203#discussion_r346403324)

> In the future if/when an attack against the current hash, we'll need a plan to transition to a new hash (which I think we need documented anyways, even with 2 hashes because the weakness could affect both of them).

**Comment by lukpueh** [comment]
This might be as simple as having the repository code changing the hash algorithm key in the [`HASHES`](https://github.com/theupdateframework/specification/blame/8cc883d70f140a3f4ffca753c2bb98d6383722d4/tuf-spec.md#L816-L817) dictionary in tuf metadata from e.g. `"shaNOW-CONSIDER-WEAK"` to `"shaMOMENTARLY-STRONG"`, and to henceforth use that algorithm to hash metadata and/or target files? 

If the server code does not yet support that algorithm, it needs to be updated.
If the client code does not yet support it, it should fail with an "unsupported hash algorithm error" and recommend to the user to update the client.

To me, two questions remain:
- Should old metadata be re-generated with the new hash algorithm?

   I lean towards yes. In the worst case a migration from shaNOW-CONSIDER-WEAK to shaMOMENTARLY-STRONG is as critical as a key rotation after a compromise, in which case we also recommend renewing all metadata. And we only need to renew non-root metadata there. So no offline key handling. Still, the client has to re-download things. But I think that’s fair.

- How does the client update itself, if it does not support the new hash algorithm?

  Simple answer: Out of band. However, to avoid that, support for new algorithms should be pushed to clients before migrating the metadata.

*UPDATE on 28/12/19: Adding answers to my questions.*

**Comment by lukpueh** [comment]
Btw and IIUC, Donald's comment only regarded the hash algorithms used to hash other metadata files and target files, do we also need to discuss keyid hash algorithm migration here? 

There's already a half-lively discussion about the scope and algorithms for keyids,  and the `keyid_hash_algorithms` feature, which is available in python-tuf but not mentioned in the tuf specification. See https://github.com/theupdateframework/tuf/issues/848.

**Comment by trishankatdatadog** [comment]
@lukpueh I agree, this is not as straightforward as it sounds like to fix

**Comment by brainwane** [comment]
Here is a rough plan for transitioning hashes:

0. get consensus that we need to turn off support for an old hash algorithm, by rough consensus of PyPI maintainers, announced to https://discuss.python.org/c/packaging
1. email out an announcement to https://mail.python.org/mailman3/lists/pypi-announce.python.org/ and put it in various other announcement media (like conference talks, Twitter, documentation, etc.)
2. put a deprecation notice in Warehouse's API output for people uploading/downloading stuff having to do with the old hash
2a. assuming we have a package preview feature https://wiki.python.org/psf/Fundable%20Packaging%20Improvements#Package_preview_feature_for_PyPI , use that to start warning uploaders in the browser UI
3. look at analytics and see how the curve is going
4. do another announcement
5. stop supporting the old algorithm and only support the new algorithm(s)

**Comment by mnm678** [comment]
As part of the transition plan, would it make sense to have some amount of time where both algorithms are supported? Maybe we can add a note about how clients can chose the hash algorithm they will use during that transition time (the most recent supported one)

**Comment by brainwane** [comment]
Right! I had been assuming that we'd STARTED the transition plan with both algorithms being supported.

Also, I'm remembering now:

> This PEP does not prescribe how package managers, such as pip, should be adapted to install or update projects from PyPI with TUF metadata.

That's a job for the TUF docs, and then detailed specification regarding the upload tooling side is going to be in PEP 480. PEP 458 is just going to be about Warehouse.

So actually a fuller plan goes like:

0. Implement new algorithm in Warehouse, and have APIs include support for old + new.
1. Announce new feature. Advise official download clients (pip and bandersnatch, let's say) and official upload tooling (probably twine, setuptools, distutils) to implement support for new hashing algorithm.
2. Once key clients have support for new hash algorithm, start defaulting to the new one.
3. get consensus that we need to turn off support for an old hash algorithm, by rough consensus of PyPI maintainers, announced to https://discuss.python.org/c/packaging
4. email out an announcement to https://mail.python.org/mailman3/lists/pypi-announce.python.org/ and put it in various other announcement media (like conference talks, Twitter, documentation, etc.)
5. Put a deprecation notice in Warehouse's API output for people uploading/downloading stuff having to do with the old hash. Assuming we have a package preview feature https://wiki.python.org/psf/Fundable%20Packaging%20Improvements#Package_preview_feature_for_PyPI , use that to start warning uploaders in the browser UI
6. Look at analytics and see how the curve is going
7. Make another announcement
8. Remove Warehouse support for the old algorithm and only support the new algorithm(s).

**Comment by lukpueh** [comment]
#76 is a first stab of getting the gist of the discussion here into the pep.

Feel free to throw rocks at it. Above all, @brainwane, let me know if you think I should add more of the details you provided (i.e. which channels to use for communication, how to assess if the adoption of the new algorithm is sufficient, etc.).

My rationale for keeping it that brief was that client and uploader workflows are not actually in the scope of PEP 458.

**Comment by brainwane** [comment]
@lukpueh I think your reasoning is good and I'm fine with the draft you wrote. Thanks.

**Comment by lukpueh** [comment]
Thanks for the review, @brainwane.

**Comment by brainwane** [comment]
Since the related PR has been merged, can we now close this?

**Comment by mnm678** [comment]
Yes, resolved via python#1253
